### ISSUE TITLE
WMPL Multicurrency support

### ISSUE THREAD

**Issue by rudolfgusta** [Zasilkovna/WooCommerce#292]
Hi,

We set up the plugin for the online store. For now, customers can pay it in SK in Euros but in CZ they get delivery for free. We have set up the services and prices for bowth in Euros. How to fix?

**Comment by uhlhosting** [comment]
Have you found some workaround for that? i believe they would need to add maybe some support for wpml in the end.

**Comment by MatyasKoval** [comment]
Hello @rudolfgusta  and @uhlhosting ,
my apologies for the late response on the original question.

Since the creation of this issue, we have released a new version of our plugin - version 1.4, which among others included a lot of fixes, changes to how free shipping is offered and computed and compatibility enhancements with other plugins.

Is this issue you have reported still happening, or has it been fixed by the newly released version?

Best regards,
Matyáš Kovaľ - Packeta E-Commerce Support

**Comment by MatyasKoval** [comment]
Hello,
as mentioned in the previous answer, since the 1.4 version of our plugin, these problems should no longer be occuring.

In case of any problems with the plugin, please let us know either by creating a new thread or at technicka.podpora@zasilkovna.cz.

Best regards,
Matyáš Kovaľ - Packeta E-Commerce Support
